# Generated by Django 5.0.1 on 2024-01-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
